package com.zipe.util.common

import kotlin.reflect.jvm.internal.impl.util.ModuleVisibilityHelper

const val SYSTEM_ADMIN = "Admin"
const val ENCODE_MS950 = "MS950"
const val ENCODE_BIG5 = "Big5"
const val ENCODE_UTF8 = "UTF-8"
const val SQLLOADER_ENCODE_UTF8 = "AL32UTF8"
var PAGE_INDEX = 0
var MAX_PAGE_COUNT = 100
var PAGE_ROW_COUNT = 10
var PAGING = 10
const val BATCH_STATUS_DESC_START = "Start"
const val BATCH_STATUS_DESC_SUCCESS_END = "SuccessEnd"
const val BATCH_STATUS_DESC_FAIL_END = "FailEnd"
const val CHANGE_FORMAT_STATUS_FAILED = "3"
const val CHANGE_FORMAT_STATUS_NOT_DONE = "0"
const val COMMA = ","
const val EMPTY = ""
const val COLON = ":"
const val PERCENT = "%"
const val DOT = "."
const val SEMICOLON = ";"
const val DASH = "-"
const val UNDERLINE = "_"
const val AT = "@"
const val SUCCESS = "success"
const val FAIL = "fail"
const val SHORT_YES = "Y"
const val SHORT_NO = "N"
const val YES = "YES"
const val NO = "NO"
const val SHORT_TRUE = "T"
const val SHORT_FALSE = "F"
const val TRUE = "TRUE"
const val FALSE = "FALSE"
const val EQUALS = "="
const val DEFAULT_THREAD_SIZE = 5
const val LINE_SEPERATOR1 = "\n"
const val LINE_SEPERATOR2 = "\r\n"
const val LINE_SEPERATOR3 = "<br/>"
const val SLASH = "/"
const val TILDE = "~"
const val EXCEL_EXTENSION = "xlsx"
const val IMAGE = "image"
const val IMAGE_JPG = "jpg"
const val IMAGE_PNG = "png"
const val SET_CONTENT_TYPE = "APPLICATION/OCTET-STREAM"
const val SET_HEADER_COOKIE = "Set-Cookie"
const val SET_HEADER_FILEDOWNLOAD_PATH = "fileDownload=true; path=/"
const val SET_HEADER_CONTENT_DISPOSITION = "Content-disposition"
const val SET_HEADER_ATTACHMENT_FILENAME = "attachment; filename="
